[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sparrow", email = "benthorpe.dev@gmail.com"},
]
dependencies = []
[tool.pdm.scripts]
dev = "uvicorn main:app --reload"
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

